import os

stock_list = ['AUROPHARMA','AXISBANK','BAJFINANCE','BPCL','BOSCHLTD','CIPLA','DRREDDY','EICHERMOT','GAIL','HCLTECH','HDFCBANK','HEROMOTOCO','HINDALCO','HINDPETRO','HINDUNILVR','HDFC','ITC','ICICIBANK','IOC','INDUSINDBK','INFY','KOTAKBANK','LT','LUPIN','M&M','MARUTI','NTPC','ONGC','POWERGRID','RELIANCE','SBIN','SUNPHARMA','TCS','TATAMOTORS','TATASTEEL','TECHM','UPL','ULTRACEMCO','VEDL','WIPRO','YESBANK','ZEEL']

for symbol in stock_list:
	os.mkdir(symbol)
